<?php

namespace EsqueletoBundle\Repository;

/**
 * CartasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartasRepository extends \Doctrine\ORM\EntityRepository
{
}
